import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopBar from "@/components/topbar/page";
import Navbar from "@/components/navbar/page";
import CallbackForm from "@/components/form/page";
import Footer from "@/components/footer/pages";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          <TopBar />
          <Navbar />
          {children}
         <div className="py-5">
           <CallbackForm/>
         </div>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
